Doc updates - Troubleshooting and other updates.
HewlettPackard/swarm-learning pull request #31
Opened 2021-07-17 14:32 UTC by RadhakrishnaJ

Main Readme - 
Added Troubleshooting section in main readme.

Download and setup - 
Corrected resources reference link used for Content Trust in Docker. 
Added statement to clarify need for referring autopass license server setup pdf.  

Troubleshooting - 
Added Troubleshooting in documents.
Added instructions to resolve 6002 Error. 

Examples - 
Added clarity for APLS IP.

FAQs - 
Updated FAQs to install custom packages for Machine Learning.

2021-07-19 05:25 UTC, suresh-ls commented on docs/FAQ.md
> +Yes. For any additional packages support to machine learning process, user has to do following.
Reword - "additional support packages"..

2021-07-19 09:31 UTC, suresh-ls commented on docs/Troubleshooting.md
> +Error code: 6002, as shown in below screenshot happens when running SL Node without starting APLS server and License setup.
Better to more specific 'SL is not able to connect to the APLS server'

2021-07-19 09:32 UTC, suresh-ls commented on docs/Troubleshooting.md
> +Browse to autopass license server management console: https://192.168.1.102:5814/autopass
We need to detail how to launch the GUI.. Please refer Issue #5

2021-07-19 11:21 UTC, RadhakrishnaJ commented on docs/FAQ.md
> +Yes. For any additional packages support to machine learning process, user has to do following.
Corrected wording.

2021-07-20 07:59 UTC, suresh-ls approved these changes

2021-07-21 12:49 UTC, ravi-ss requested changes

2021-07-21 12:49 UTC, ravi-ss commented on docs/Troubleshooting.md
> +'your install directory/swarm-learning/bin/run-apls'
Is this the convention that we are using now?
In the original version of the documentation, we had said that we were assuming the install directory to be swarm-learning or something like that. Have we removed this?
I would prefer swarm-learning-install-dir to your-install-dir. And, please format code and artifacts as code blocks.

2021-07-21 12:49 UTC, ravi-ss commented on docs/Troubleshooting.md
> +###### Check APLS status:
Did not follow. What do you mean by "APLS status" here? Did that docker ps command above not check status?

2021-07-21 12:49 UTC, ravi-ss commented on docs/Troubleshooting.md
> +> NOTE: For this explanation IP 192.168.1.102 is used – replace this IP address with your license host system IP address (Do NOT use localhost / 127.0.0.1)
"license host system" should be rephrased. How about "the host system on which the license server container is running"?

2021-07-21 12:49 UTC, ravi-ss commented on docs/Troubleshooting.md
> +Browse to autopass license server management console: https://192.168.1.102:5814/autopass.
"Open https://192.168.1.102:5814/autopass from a web browser"?
"Use a web browser to connect to https://192.168.1.102:5814/autopass"?
And, use either APLS or **A**utopass **L**icense **S**erver

2021-07-21 12:49 UTC, ravi-ss commented on docs/Troubleshooting.md
> +> NOTE: If you can run a browser on the host machine where you ran the "run-apls" script, You can now connect to the License server using https://192.168.1.102:5814/autopass from a browser.
Did not understand this

2021-07-21 12:49 UTC, ravi-ss commented on docs/Troubleshooting.md
> +Otherwise, In the APLS login screen, login using "admin/password".
Why do we need all these details? If at all it is relevant, it should go into other sections like Installation or Configuration. Have pointers to those sections here.
If the browser cannot connect, it does not necessarily mean that APLS is not running &mdash; for instance, he could have an incorrect network proxy configuration. Preferrably, we should not make such assumptions and presumptions. Instead, let him work with his admins and ensure connectivity.
That APLS password is the initial password &mdash; it is not valid for subsequent logins.

2021-07-21 12:49 UTC, ravi-ss commented on docs/Troubleshooting.md
> +   If you are seeing the above screenshot in your APLS Management console, it means your license setup is complete.
Again, do we really require so much handholding here?

2021-07-21 12:49 UTC, ravi-ss commented on docs/FAQ.md
> +sudo is not required to launch the container, if docker is configured to run as a non-root user. Refer [Manage Docker as a non-root user](URL.md#16-manage-docker-as-a-non-root-user-httpsdocsdockercom
> if docker is configured to run as a non-root user
Is this correct? What do you mean by "docker" here? The docker daemon? Is it really running with non-root privileges?

2021-07-21 12:49 UTC, ravi-ss commented on docs/FAQ.md
>  ## Can one add new python packages in Swarm Learning?
Should it not be "Python"?

2021-07-21 12:49 UTC, ravi-ss commented on docs/FAQ.md
> +4. As usual run the container using run-sl command.
To the extent possible, provide exact commands and line numbers. Readers frequently copy-paste these instructions and get surprised when it does not work.

2021-07-21 12:49 UTC, ravi-ss commented on docs/setup.md
> +protected. User needs to login to docker registry using HPE Passport email id and password 'hpe_eval'. All Swarm Learning images are signed by HPE with the name as 'hpe-ai-swarm-learning'. Users can
So, when I click that link, I see 20 references. Which is the relevant one?

2021-07-21 12:49 UTC, ravi-ss commented on docs/setup.md
>  The default username is, ``"admin"``, and the password, ``"password"``.
Why those double quotes? It prevents readers from copy-pasting.

2021-07-21 12:49 UTC, ravi-ss commented on docs/setup.md
>  > NOTE: Whenever the container running the License Server (apls) is stopped or the host system running the License Sever reboots, the  License Server needs to be started and the licenses have to be r
Should be **APLS**, not _apls_.

2021-07-21 12:49 UTC, ravi-ss commented on docs/setup.md
>  > HPE recommends not to stop the License Server container once it is started.
Can you make this stronger? Recommendations can be ignored &mdash; and, generally speaking, I would expect a product to work properly even when I ignore a recommendation. Our case is different &mdash; we simply do not want users to stop APLS.

2021-07-21 12:49 UTC, ravi-ss commented on examples/fraud-detection-keras/README.md
> +-	APLS_IP: IP address of the host where license server is running (Do NOT use localhost / 127.0.0.1).
External IP?

2021-07-21 12:49 UTC, ravi-ss commented on examples/fraud-detection-keras/README.md
> +   ``APLS_IP=<License Host Server IP (Do NOT use localhost / 127.0.0.1)>``
This is applicable for any and every IP the user specifies. Can we have a single, big warning somewhere instead of reiterating all over the place?

2021-07-21 14:27 UTC, RadhakrishnaJ commented on docs/Troubleshooting.md
> +####    Custom message: Error in communicating with server https://HOST_SYSTEM_IP:5814 (default port) ####
Formatted Error messages as code block.

2021-07-21 14:29 UTC, RadhakrishnaJ commented on docs/Troubleshooting.md
> +Run docker ps | grep apls  -> If apls container is not running, then license server is not running, and you need to start it using
Formatted as code block. If APLS name changes, this section needs update.

2021-07-21 14:30 UTC, RadhakrishnaJ commented on docs/Troubleshooting.md
> +'your install directory/swarm-learning/bin/run-apls'
Corrected swarm-learning-install-dir and formatted as code block.

2021-07-21 14:33 UTC, RadhakrishnaJ commented on docs/Troubleshooting.md
> +> NOTE: For this explanation IP 192.168.1.102 is used – replace this IP address with your license host system IP address (Do NOT use localhost / 127.0.0.1)
corrected wording

2021-07-21 14:34 UTC, RadhakrishnaJ commented on docs/Troubleshooting.md
> +Browse to autopass license server management console: https://192.168.1.102:5814/autopass.
Corrected wording and used APLS.

2021-07-21 14:38 UTC, RadhakrishnaJ commented on docs/Troubleshooting.md
> +Otherwise, In the APLS login screen, login using "admin/password".
Most of the time license server issues are first time user issues, once first time is setup they will good. Detailed instructions are added to support first time user.

2021-07-21 14:40 UTC, RadhakrishnaJ commented on docs/Troubleshooting.md
> +   If you are seeing the above screenshot in your APLS Management console, it means your license setup is complete.
Seeing the pattern of license server issues and explanation, decided to have screen shots and detailed instructions to help first time users.

2021-07-21 14:45 UTC, RadhakrishnaJ commented on docs/FAQ.md
> +sudo is not required to launch the container, if docker is configured to run as a non-root user. Refer [Manage Docker as a non-root user](URL.md#16-manage-docker-as-a-non-root-user-httpsdocsdockercom
Corrected reference link to point the resources. Corrected name to match as in references section, so that it is easy for user get docker documentation.

2021-07-22 04:57 UTC, RadhakrishnaJ commented on docs/FAQ.md
>  ## Can one add new python packages in Swarm Learning?
Done

2021-07-22 05:02 UTC, RadhakrishnaJ commented on docs/FAQ.md
> +4. As usual run the container using run-sl command.
Scripts can change frequently, may be giving lines needs frequent revisit of this. These instructions are not to be used as is, user needs to modify to match with his local image.

2021-07-22 05:04 UTC, RadhakrishnaJ commented on docs/setup.md
> +protected. User needs to login to docker registry using HPE Passport email id and password 'hpe_eval'. All Swarm Learning images are signed by HPE with the name as 'hpe-ai-swarm-learning'. Users can
Earlier one was going to resources main heading. Now it is going to page where relevant link is available, I have maintained name to match with name in references, using the name user has to refer the link. Didn't find any other better way.

2021-07-22 05:09 UTC, RadhakrishnaJ commented on docs/setup.md
>  The default username is, ``"admin"``, and the password, ``"password"``.
Done

2021-07-22 05:10 UTC, RadhakrishnaJ commented on docs/setup.md
>  > NOTE: Whenever the container running the License Server (apls) is stopped or the host system running the License Sever reboots, the  License Server needs to be started and the licenses have to be r
Done

2021-07-22 05:15 UTC, RadhakrishnaJ commented on docs/setup.md
>  > HPE recommends not to stop the License Server container once it is started.
Moved it out of Notes. Made it little bold with small font.

2021-07-23 06:08 UTC, RadhakrishnaJ commented on examples/fraud-detection-keras/README.md
> +-	APLS_IP: IP address of the host where license server is running (Do NOT use localhost / 127.0.0.1).
No update done for this. Browsed for external IP, it has multiple definitions.

2021-07-23 08:38 UTC, RadhakrishnaJ commented on examples/fraud-detection-keras/README.md
> +   ``APLS_IP=<License Host Server IP (Do NOT use localhost / 127.0.0.1)>``
In Examples - removed repeated occurrences of Do NOT use localhost / 127.0.0.1.

2021-07-23 08:40 UTC, RadhakrishnaJ commented on docs/Troubleshooting.md
> +Otherwise, In the APLS login screen, login using "admin/password".
Moved these steps from Troubleshooting to setup. Added link in troubleshooting to setup.

2021-07-23 09:36 UTC, RadhakrishnaJ commented on docs/Troubleshooting.md
> +   If you are seeing the above screenshot in your APLS Management console, it means your license setup is complete.
Moved content to Setup documentation. Only one screen shot used to show how management console looks after successful license install.

2021-07-23 09:40 UTC, RadhakrishnaJ commented
Completed rework. Please perform review.

2021-07-27 15:34 UTC, suresh-ls commented on docs/setup.md
> +#### Running AutoPass License Server (APLS)
Looks too cluttered :-)   Can we number them ?  Say 1. Running AutoPass....     2) Setting up Swarm License  at the very least...

2021-07-27 15:37 UTC, suresh-ls approved these changes

2021-07-28 05:16 UTC, RadhakrishnaJ commented on docs/Troubleshooting.md
> +> NOTE: If you can run a browser on the host machine where you ran the "run-apls" script, You can now connect to the License server using https://192.168.1.102:5814/autopass from a browser.
Added steps to connect with APLS GUI.

2021-07-28 05:21 UTC, RadhakrishnaJ commented on docs/setup.md
> +#### Running AutoPass License Server (APLS)
Will handle adding bullets in next pull.

2021-07-28 06:45 UTC, ravi-ss requested changes

2021-07-28 06:45 UTC, ravi-ss commented on docs/Troubleshooting.md
> +Troubleshooting provides solutions to commonly observed issues during Swarm set up and execution.
Please use **Swarm Learning** everywhere &mdash; not Swarm

2021-07-28 06:45 UTC, ravi-ss commented on docs/Troubleshooting.md
> +Error code: 6002, as shown in below screenshot happens when SL is not able to connect to the APLS server.
SL = Swarm Learning?
I prefer you rephrase this as "Swarm Learning components" or something similar. SL is confusing because we also use it to refer to the ML nodes.

2021-07-28 06:45 UTC, ravi-ss commented on docs/Troubleshooting.md
> +Run ``docker ps | grep apls``  -> If apls container is not running, then license server is not running, and you need to start it using
Where is this **apls** name hardcoded? It is not in `run-apls`.

I repeat again:
1. Do not provide instructions that are definitely wrong.
2. To the extent possible, provide exact commands &mdash; commands that people can copy-paste.

So, for this specific case:
1. Just say, "Run `docker ps` and check whether APLS is running". Do not include the `grep`.
2. If you really want to filter the results, use a filter on the image, not container. See `genDockerExec` in `common`: `docker ps --format {{.Names}} --filter=ancestor=hub.myenterpriselicense.hpe.com/hpe_eval/swarm-learning/apls:0.3.0`

2021-07-28 06:45 UTC, ravi-ss commented on docs/Troubleshooting.md
> +##### 1. Running AutoPass License Server (APLS)
Verify APLS is running

2021-07-28 06:45 UTC, ravi-ss commented on docs/Troubleshooting.md
> +If the browser response is, "this site can’t be reached" / "refused to connect" - It means APLS is not running correctly. Restart run-apls script as mentioned above.
If the browser cannot connect, verify the network proxy settings, firewall policies, etc. that are in effect. If required, work with your network administrator to resolve them.

Do not advice restarting APLS. We definitely discourage that.

2021-07-28 06:45 UTC, ravi-ss commented on docs/setup.md
> +###### Browse APLS Management console:
"Access" or "Connect to" instead of "browse"?

2021-07-28 06:45 UTC, ravi-ss commented on docs/setup.md
> +> NOTE: For this explanation IP 192.168.1.102 is used – replace this IP address with the host system IP address on which the license server container is running.
Should we use the same IP that we have in our examples?

2021-07-28 06:45 UTC, ravi-ss commented on docs/setup.md
> +If the browser response is, "this site can’t be reached" / "refused to connect" - It means APLS is not running correctly. Restart run-apls script as mentioned above.
How about something on these lines?

Access the License Server's management console by using a browser to connect to https://192.160.1.102:5814/.

NOTE:
1. These instructions assume the IP of the system on which the License Server is running is 192.168.1.102.
2. They also assume the container port has been published and that the external port is 5814.
3. Modify these values to match the actual IP and external port on your system.
4. If the browser cannot connect to the management console, check your network proxy settings and firewall policies. Consider techniques like port forwarding to workaround firewall policies. If necessary, work with your network administrator to diagnose and resolve connectivity problems.

2021-07-28 07:55 UTC, RadhakrishnaJ commented on docs/Troubleshooting.md
> +Run ``docker ps | grep apls``  -> If apls container is not running, then license server is not running, and you need to start it using
updated to use only docker ps.

2021-07-28 07:56 UTC, RadhakrishnaJ commented on docs/Troubleshooting.md
> +If the browser response is, "this site can’t be reached" / "refused to connect" - It means APLS is not running correctly. Restart run-apls script as mentioned above.
Added this statement.

2021-07-28 08:03 UTC, RadhakrishnaJ commented on docs/setup.md
> +> NOTE: For this explanation IP 192.168.1.102 is used – replace this IP address with the host system IP address on which the license server container is running.
I don't see any APLS host machine IP in our examples. As explanation is given the used IP, I hope this is good enough.

2021-07-28 08:07 UTC, RadhakrishnaJ commented on docs/setup.md
> +###### Browse APLS Management console:
used Access

2021-07-28 13:18 UTC, RadhakrishnaJ commented on docs/setup.md
> +If the browser response is, "this site can’t be reached" / "refused to connect" - It means APLS is not running correctly. Restart run-apls script as mentioned above.
Updated documentation.

2021-07-30 07:16 UTC, ravi-ss approved these changes

2021-07-30 07:16 UTC, ravi-ss commented on docs/Troubleshooting.md
> +If the browser response is, "this site can’t be reached" / "refused to connect".
Delete this

2021-07-30 07:41 UTC, RadhakrishnaJ commented on docs/Troubleshooting.md
> +If the browser response is, "this site can’t be reached" / "refused to connect".
Done

2021-07-30 07:45 UTC, merged