SwarmCallback and additional doc updates
HewlettPackard/swarm-learning pull request #43
Opened 2021-08-11 06:23 UTC by RadhakrishnaJ

1. SwarmCallback api updated to include additional parameters.
2. Added FAQ on how to know SN is successfully started.
3. Added Architecture in prerequisite.

2021-08-12 12:32 UTC, suresh-ls commented on docs/ml_algorithm.md
> +    - snapshot – Node always checks in the weights that it had when it reached the stopping criterion, it will not accept merged weights.
For uniformity with previous point:
change "checks in" -> "contributes"

2021-08-12 12:32 UTC, suresh-ls approved these changes

2021-08-13 05:51 UTC, RadhakrishnaJ commented on docs/ml_algorithm.md
> +    - snapshot – Node always checks in the weights that it had when it reached the stopping criterion, it will not accept merged weights.
updated wording.

2021-08-16 06:20 UTC, sathya-SL requested changes

2021-08-16 06:20 UTC, sathya-SL commented on docs/ml_algorithm.md
>      feature should be used for tuning the sync interval. This feature is
should be used for tuning the sync interval. -> should be used for automatically generating the sync interval.

2021-08-16 06:20 UTC, sathya-SL commented on docs/ml_algorithm.md
> +-   'checkin_model_on_train_end' specifies the merge behaviour of a SL node *after* it has achieved stopping criterion and it is waiting for all other peers to complete their training. During this pe
highlight this part "SL node will not train model with local data"

2021-08-16 06:20 UTC, sathya-SL commented on docs/ml_algorithm.md
> +    - active – Node behaves as if it is in active training.
Node behaves as if it is in active training.  "But will not train merged model with local data as mentioned above."
- make the point that even though it behaves like active training it will not actually train using local data ...

2021-08-16 06:36 UTC, RadhakrishnaJ commented on docs/ml_algorithm.md
>      feature should be used for tuning the sync interval. This feature is
Done

2021-08-16 06:36 UTC, RadhakrishnaJ commented on docs/ml_algorithm.md
> +-   'checkin_model_on_train_end' specifies the merge behaviour of a SL node *after* it has achieved stopping criterion and it is waiting for all other peers to complete their training. During this pe
Highlighted.

2021-08-16 06:36 UTC, RadhakrishnaJ commented on docs/ml_algorithm.md
> +    - active – Node behaves as if it is in active training.
Done.

2021-08-16 06:40 UTC, sathya-SL approved these changes

2021-08-16 06:47 UTC, RadhakrishnaJ commented
Adding following content to Master. 
SwarmCallback api updated to include additional parameters.
Added FAQ on how to know SN is successfully started.
Added Architecture in prerequisite.

2021-08-16 06:47 UTC, merged