Use non default ports
HewlettPackard/swarm-learning pull request #52
Opened 2021-09-15 16:08 UTC by girisairam450

2021-09-16 04:55 UTC, ravi-ss requested changes

2021-09-16 04:55 UTC, ravi-ss commented on swarm-learning/bin/common
> +            if [[ -n "${5}" ]]
Update the comments for this function

2021-09-16 04:55 UTC, ravi-ss commented on swarm-learning/bin/common
> +        --ssh-user)
Update the help text.

Is no change required to the README files?

2021-09-16 05:20 UTC, suresh-ls commented on swarm-learning/bin/common
> +            if [[ -n "${5}" ]]
Yes, its unclear what are $5 and $6.

2021-09-16 05:28 UTC, suresh-ls commented on swarm-learning/bin/common
> +        --ssh-user)
- How  is this  --ssh-user different from the -user above ??

- Do we need a short name for this, just for uniformity as all others have short forms..

2021-09-16 05:30 UTC, suresh-ls approved these changes

2021-09-16 16:38 UTC, girisairam450 commented on swarm-learning/bin/common
> +            if [[ -n "${5}" ]]
added appropriate comments

2021-09-17 16:25 UTC, girisairam450 commented on swarm-learning/bin/common
> +        --ssh-user)
@suresh-ls 
--ssh-user is for connecting to spire server via this user. While --user is within the given node. run-sn uses long forms while init-workspace uses short forms. So uniformity is met.
@ravi-ss 
updated the read me and help text of this function.

2021-09-20 06:50 UTC, ravi-ss requested changes

2021-09-20 06:50 UTC, ravi-ss commented on docs/RunningSL.md
> +-   ``--ssh-port <ssh port number>``
Fix alignment on lines 107-109 and 358-362.

2021-09-20 06:50 UTC, ravi-ss commented on docs/RunningSL.md
> +
This should be rephrased and documented under the common options

2021-09-20 06:50 UTC, ravi-ss commented on swarm-learning/bin/common
> +#   4. Optional ssh port and ssh user. If not specified the connection will be
This is not correct. This should be:
   * 4 - descriptive name
   * 5 - ssh port
   * 6 - ssh user

2021-09-20 06:50 UTC, ravi-ss commented on swarm-learning/bin/common
> +        --ssh-user)
You should document these new options in the usage function

2021-09-20 10:37 UTC, girisairam450 commented on swarm-learning/bin/common
> +#      happen as the mentioned user.
add if not specified it will be taken as current user.

2021-09-20 10:39 UTC, girisairam450 commented on swarm-learning/bin/common
> +        --ssh-user)
add it to printCommonUsage

2021-09-20 11:03 UTC, girisairam450 commented on docs/RunningSL.md
> +
This parameter specifies the port number on which the SSH server is listening. It is optional. 
It should be specified in a multi-system cluster environment when the SSH servers are not listening on the default SSH port.

This parameter specifies the user name to use when establishing an SSH connection. It is optional. When it is not specified, the current user's login name is used.

2021-09-20 11:12 UTC, girisairam450 commented on docs/Prerequisites.md
> +        >   *NOTE*: If needed, a non-default port SSH connection is possible through ssh port and ssh user options.
Not needed

2021-09-20 12:20 UTC, girisairam450 commented on swarm-learning/bin/common
> +        --ssh-user)
added to common usage

2021-09-20 12:25 UTC, girisairam450 commented on docs/RunningSL.md
> +
rephrased.

2021-09-21 04:52 UTC, suresh-ls approved these changes
Looks good.

2021-09-21 05:05 UTC, ravi-ss approved these changes

2021-09-21 05:05 UTC, ravi-ss commented on swarm-learning/bin/common
> +    printf -- "\tDefault: 22, if ssh listener doesn't use any custom port\n\n"
The port on which the SSH server is listening.
Default: 22

2021-09-21 05:05 UTC, ravi-ss commented on swarm-learning/bin/common
> +    printf -- "\tDefault: current user, if not specified\n\n"
The user name to use when establishing a SSH connection.
Default: current user

2021-09-21 05:12 UTC, girisairam450 commented on swarm-learning/bin/common
> +    printf -- "\tDefault: 22, if ssh listener doesn't use any custom port\n\n"
updated

2021-09-21 05:13 UTC, girisairam450 commented on swarm-learning/bin/common
> +    printf -- "\tDefault: current user, if not specified\n\n"
updated

2021-09-21 05:15 UTC, merged